param(
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

function Get-TextSignature {
    param([string]$Text)
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($Text)
    $hash = [System.Security.Cryptography.SHA256]::Create().ComputeHash($bytes)
    return -join ($hash | ForEach-Object { $_.ToString('x2') })
}

function New-ZipFromDirectory {
    param(
        [string]$SourceDirectory,
        [string]$DestinationZip
    )

    Add-Type -AssemblyName System.IO.Compression
    Add-Type -AssemblyName System.IO.Compression.FileSystem

    if (Test-Path $DestinationZip) {
        Remove-Item -LiteralPath $DestinationZip -Force
    }

    $sourceRoot = (Resolve-Path $SourceDirectory).Path.TrimEnd('\', '/')
    $zipFile = [System.IO.File]::Open($DestinationZip, [System.IO.FileMode]::CreateNew)
    try {
        $archive = New-Object System.IO.Compression.ZipArchive($zipFile, [System.IO.Compression.ZipArchiveMode]::Create, $false)
        try {
            Get-ChildItem -LiteralPath $sourceRoot -Recurse -Force -File | ForEach-Object {
                $relativePath = $_.FullName.Substring($sourceRoot.Length + 1).Replace('\', '/')
                $entry = $archive.CreateEntry($relativePath, [System.IO.Compression.CompressionLevel]::Optimal)
                $entry.LastWriteTime = $_.LastWriteTime

                $inputStream = [System.IO.File]::OpenRead($_.FullName)
                try {
                    $outputStream = $entry.Open()
                    try {
                        $inputStream.CopyTo($outputStream)
                    }
                    finally {
                        $outputStream.Dispose()
                    }
                }
                finally {
                    $inputStream.Dispose()
                }
            }
        }
        finally {
            $archive.Dispose()
        }
    }
    finally {
        $zipFile.Dispose()
    }
}

$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$PythonVersion = '3.13.14'
$PythonAbiTag = '313'
$RequirementsPath = Join-Path $RepoRoot 'runtime-requirements-v1.txt'
$EmbedZipPath = Join-Path $RepoRoot "src-tauri\python-embed\python-$PythonVersion-embed-amd64.zip"
$GetPipPath = Join-Path $RepoRoot 'src-tauri\python-embed\get-pip.py'
$ResourceDir = Join-Path $RepoRoot 'src-tauri\python-runtime'
$ZipPath = Join-Path $ResourceDir 'python-runtime-v1.zip'
$SignaturePath = Join-Path $ResourceDir 'python-runtime-v1.signature'
$StageRoot = Join-Path $RepoRoot '.agentvis-build\python-runtime-v1'
$RuntimeRoot = Join-Path $StageRoot 'python-v1'
$ArchiveSmokeRoot = Join-Path $StageRoot 'archive-smoke'
$VenvRoot = Join-Path $RuntimeRoot '.venv'
$ScriptsDir = Join-Path $VenvRoot 'Scripts'
$LibDir = Join-Path $VenvRoot 'Lib'
$SitePackagesDir = Join-Path $LibDir 'site-packages'
$PythonExe = Join-Path $ScriptsDir 'python.exe'

if (-not (Test-Path $RequirementsPath)) {
    throw "Missing requirements file: $RequirementsPath"
}
if (-not (Test-Path $EmbedZipPath)) {
    throw "Missing embedded Python zip: $EmbedZipPath"
}
if (-not (Test-Path $GetPipPath)) {
    throw "Missing get-pip.py: $GetPipPath"
}

New-Item -ItemType Directory -Path $ResourceDir -Force | Out-Null

$scriptPath = if ($PSCommandPath) { $PSCommandPath } else { $MyInvocation.MyCommand.Path }
$signatureSource = @(
    "requirements=$((Get-FileHash $RequirementsPath -Algorithm SHA256).Hash)"
    "embedded=$((Get-FileHash $EmbedZipPath -Algorithm SHA256).Hash)"
    "getpip=$((Get-FileHash $GetPipPath -Algorithm SHA256).Hash)"
    "script=$((Get-FileHash $scriptPath -Algorithm SHA256).Hash)"
) -join "`n"
$signature = Get-TextSignature $signatureSource

if (-not $Force -and (Test-Path $ZipPath) -and (Test-Path $SignaturePath)) {
    $existingSignature = (Get-Content $SignaturePath -Raw).Trim()
    if ($existingSignature -eq $signature) {
        Write-Host "python-runtime-v1.zip is up to date."
        exit 0
    }
}

if (Test-Path $StageRoot) {
    Remove-Item -LiteralPath $StageRoot -Recurse -Force
}
New-Item -ItemType Directory -Path $ScriptsDir -Force | Out-Null
New-Item -ItemType Directory -Path $SitePackagesDir -Force | Out-Null

Write-Host "Extracting embedded Python..."
Expand-Archive -Path $EmbedZipPath -DestinationPath $ScriptsDir -Force

$pthPath = Join-Path $ScriptsDir "python$PythonAbiTag._pth"
@(
    "python$PythonAbiTag.zip"
    '.'
    '..\Lib'
    '..\Lib\site-packages'
    'import site'
) | Set-Content -Path $pthPath -Encoding ASCII

$siteCustomize = @'
# Auto-generated by AgentVis runtime packaging.
import os
import sys
from pathlib import Path

_AGENTVIS_DLL_DIR_HANDLES = []

def _agentvis_add_dll_dir(path):
    try:
        resolved = Path(path).resolve()
        if hasattr(os, "add_dll_directory") and resolved.exists():
            _AGENTVIS_DLL_DIR_HANDLES.append(os.add_dll_directory(str(resolved)))
    except (OSError, ValueError):
        pass

_agentvis_candidate_dirs = [
    Path(sys.executable).resolve().parent,
    Path(getattr(sys, "base_prefix", sys.prefix)).resolve(),
    Path(getattr(sys, "base_exec_prefix", sys.exec_prefix)).resolve(),
    Path(sys.prefix).resolve(),
]
_agentvis_seen = set()
for _agentvis_dir in _agentvis_candidate_dirs:
    _agentvis_key = str(_agentvis_dir).lower()
    if _agentvis_key not in _agentvis_seen:
        _agentvis_seen.add(_agentvis_key)
        _agentvis_add_dll_dir(_agentvis_dir)

def _agentvis_add_entry_script_dir():
    try:
        if not sys.argv:
            return
        argv0 = sys.argv[0]
        if not argv0 or argv0 in {"-c", "-m"}:
            return
        entry = Path(argv0)
        if not entry.is_absolute():
            entry = Path.cwd() / entry
        if not entry.is_file():
            return
        script_dir = str(entry.resolve().parent)
        if script_dir not in sys.path:
            sys.path.insert(0, script_dir)
    except (OSError, ValueError):
        pass

_agentvis_add_entry_script_dir()
'@
$siteCustomize | Set-Content -Path (Join-Path $SitePackagesDir 'sitecustomize.py') -Encoding UTF8

$env:PIP_DISABLE_PIP_VERSION_CHECK = '1'
$env:PYTHONUTF8 = '1'
$env:PYTHONDONTWRITEBYTECODE = '1'

Write-Host "Bootstrapping pip..."
& $PythonExe $GetPipPath --prefix $VenvRoot --no-warn-script-location
if ($LASTEXITCODE -ne 0) {
    throw "get-pip.py failed with exit code $LASTEXITCODE"
}

$pipMirrorArgs = @(
    '--index-url', 'http://mirrors.aliyun.com/pypi/simple/'
    '--extra-index-url', 'http://pypi.tuna.tsinghua.edu.cn/simple/'
    '--extra-index-url', 'https://pypi.org/simple/'
    '--trusted-host', 'mirrors.aliyun.com'
    '--trusted-host', 'pypi.tuna.tsinghua.edu.cn'
)

Write-Host "Installing base runtime packages..."
& $PythonExe -m pip install --prefix $VenvRoot -r $RequirementsPath --no-warn-script-location @pipMirrorArgs
if ($LASTEXITCODE -ne 0) {
    throw "Base package installation failed with exit code $LASTEXITCODE"
}

$modules = @(
    'requests'
    'httpx'
    'curl_cffi'
    'pydantic'
    'ddgs'
    'bs4'
    'lxml'
    'trafilatura'
    'pypdf'
    'pdf2image'
    'docx'
    'pptx'
    'openpyxl'
    'markdown'
    'yaml'
    'chardet'
    'dateutil'
    'tabulate'
    'jinja2'
    'dotenv'
    'matplotlib'
    'PIL'
    'plotly'
    'numpy'
    'pandas'
    'psutil'
    'tqdm'
    'setuptools'
    'wheel'
    'pip_system_certs'
)
$moduleLiteral = ($modules | ForEach-Object { "'$_'" }) -join ','
$smokeScript = "import ssl, importlib.util, sys; print(ssl.OPENSSL_VERSION); modules=[$moduleLiteral]; missing=[m for m in modules if importlib.util.find_spec(m) is None]; sys.exit('missing base modules: ' + ', '.join(missing)) if missing else print('prebuilt runtime ok')"
$ScriptDirSmokeRoot = Join-Path $StageRoot 'script-dir-smoke'
$ScriptDirSmokeEntry = Join-Path $ScriptDirSmokeRoot 'entry.py'

Write-Host "Running smoke checks..."
& $PythonExe -c $smokeScript
if ($LASTEXITCODE -ne 0) {
    throw "Runtime smoke check failed with exit code $LASTEXITCODE"
}
& $PythonExe -m pip --version
if ($LASTEXITCODE -ne 0) {
    throw "pip smoke check failed with exit code $LASTEXITCODE"
}
if (Test-Path $ScriptDirSmokeRoot) {
    Remove-Item -LiteralPath $ScriptDirSmokeRoot -Recurse -Force
}
New-Item -ItemType Directory -Path $ScriptDirSmokeRoot -Force | Out-Null
Set-Content -Path (Join-Path $ScriptDirSmokeRoot 'helper_module.py') -Value 'VALUE = "script-dir-import-ok"' -Encoding ASCII
Set-Content -Path $ScriptDirSmokeEntry -Value 'import helper_module; print(helper_module.VALUE)' -Encoding ASCII
& $PythonExe $ScriptDirSmokeEntry
if ($LASTEXITCODE -ne 0) {
    throw "Script directory import smoke check failed with exit code $LASTEXITCODE"
}

Write-Host "Creating python-runtime-v1.zip..."
New-ZipFromDirectory -SourceDirectory $RuntimeRoot -DestinationZip $ZipPath

if (Test-Path $ArchiveSmokeRoot) {
    Remove-Item -LiteralPath $ArchiveSmokeRoot -Recurse -Force
}
New-Item -ItemType Directory -Path $ArchiveSmokeRoot -Force | Out-Null

Write-Host "Verifying zipped runtime..."
Expand-Archive -Path $ZipPath -DestinationPath $ArchiveSmokeRoot -Force
$ArchiveSmokePythonExe = Join-Path $ArchiveSmokeRoot '.venv\Scripts\python.exe'
& $ArchiveSmokePythonExe -c $smokeScript
if ($LASTEXITCODE -ne 0) {
    throw "Zipped runtime smoke check failed with exit code $LASTEXITCODE"
}
& $ArchiveSmokePythonExe $ScriptDirSmokeEntry
if ($LASTEXITCODE -ne 0) {
    throw "Zipped runtime script directory import smoke check failed with exit code $LASTEXITCODE"
}

Set-Content -Path $SignaturePath -Value $signature -Encoding ASCII
Write-Host "Wrote $ZipPath"
